package shadow.examples;

import shadow.annotations.ColumnMap;
import shadow.annotations.ID;
import shadow.annotations.PersistentClass;

@PersistentClass(table = "dog_table")
public class Dog {
	
	@ID(autogenerated = true)
	@ColumnMap(column = "id")
	private long id;

	@ColumnMap(column = "column_name")
	public String name;

	@ColumnMap(column = "column_age")
	public int age;
	
	public Dog(){
		
	}
	
	public Dog(String name, int age){
		this.name = name;
		this.age = age;
	}

	public String bark(){
		return "My name is " + this.name + " and I'm " + this.age + " years old, woof."; 
	}
	
	public static void print_a_dog(Dog dog){
		System.out.println("Dog Name: " + dog.name + " Dog Age: " + dog.age); 
		
	}
}